generator:
  class: sfDoctrineGenerator
  param:
    model_class:           persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
           title: Listado de personas
           display: [Idpersona, Nombre, Apellidos, Edad, Nif, Idclub]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
