<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Jornada', 'doctrine');

/**
 * BaseJornada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idjornada
 * @property integer $numjornada
 * @property timestamp $fechajornada
 * @property string $nombre
 * @property Doctrine_Collection $Clasificacion
 * @property Doctrine_Collection $Partido
 * 
 * @method integer             getIdjornada()     Returns the current record's "idjornada" value
 * @method integer             getNumjornada()    Returns the current record's "numjornada" value
 * @method timestamp           getFechajornada()  Returns the current record's "fechajornada" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method Doctrine_Collection getClasificacion() Returns the current record's "Clasificacion" collection
 * @method Doctrine_Collection getPartido()       Returns the current record's "Partido" collection
 * @method Jornada             setIdjornada()     Sets the current record's "idjornada" value
 * @method Jornada             setNumjornada()    Sets the current record's "numjornada" value
 * @method Jornada             setFechajornada()  Sets the current record's "fechajornada" value
 * @method Jornada             setNombre()        Sets the current record's "nombre" value
 * @method Jornada             setClasificacion() Sets the current record's "Clasificacion" collection
 * @method Jornada             setPartido()       Sets the current record's "Partido" collection
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJornada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jornada');
        $this->hasColumn('idjornada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numjornada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fechajornada', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Clasificacion', array(
             'local' => 'idjornada',
             'foreign' => 'idjornada'));

        $this->hasMany('Partido', array(
             'local' => 'idjornada',
             'foreign' => 'idjornada'));
    }
}