<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusuario
 * @property integer $idpersona
 * @property Persona $Persona
 * 
 * @method integer getIdusuario() Returns the current record's "idusuario" value
 * @method integer getIdpersona() Returns the current record's "idpersona" value
 * @method Persona getPersona()   Returns the current record's "Persona" value
 * @method Usuario setIdusuario() Sets the current record's "idusuario" value
 * @method Usuario setIdpersona() Sets the current record's "idpersona" value
 * @method Usuario setPersona()   Sets the current record's "Persona" value
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idpersona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'idpersona',
             'foreign' => 'idpersona'));
    }
}