<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comentario', 'doctrine');

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcomentario
 * @property integer $idnoticia
 * @property string $idusuario
 * @property string $cuerpo
 * @property string $avatar
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Noticia $Noticia
 * @property SfGuardUserProfile $SfGuardUserProfile
 * 
 * @method integer            getIdcomentario()       Returns the current record's "idcomentario" value
 * @method integer            getIdnoticia()          Returns the current record's "idnoticia" value
 * @method string             getIdusuario()          Returns the current record's "idusuario" value
 * @method string             getCuerpo()             Returns the current record's "cuerpo" value
 * @method string             getAvatar()             Returns the current record's "avatar" value
 * @method timestamp          getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()          Returns the current record's "updated_at" value
 * @method Noticia            getNoticia()            Returns the current record's "Noticia" value
 * @method SfGuardUserProfile getSfGuardUserProfile() Returns the current record's "SfGuardUserProfile" value
 * @method Comentario         setIdcomentario()       Sets the current record's "idcomentario" value
 * @method Comentario         setIdnoticia()          Sets the current record's "idnoticia" value
 * @method Comentario         setIdusuario()          Sets the current record's "idusuario" value
 * @method Comentario         setCuerpo()             Sets the current record's "cuerpo" value
 * @method Comentario         setAvatar()             Sets the current record's "avatar" value
 * @method Comentario         setCreatedAt()          Sets the current record's "created_at" value
 * @method Comentario         setUpdatedAt()          Sets the current record's "updated_at" value
 * @method Comentario         setNoticia()            Sets the current record's "Noticia" value
 * @method Comentario         setSfGuardUserProfile() Sets the current record's "SfGuardUserProfile" value
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('idcomentario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idnoticia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idusuario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cuerpo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('avatar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Noticia', array(
             'local' => 'idnoticia',
             'foreign' => 'idnoticia'));

        $this->hasOne('SfGuardUserProfile', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario'));
    }
}