<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Equipo', 'doctrine');

/**
 * BaseEquipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idequipo
 * @property integer $numjugadores
 * @property string $nombre
 * @property integer $idclub
 * @property string $imagen
 * @property Club $Club
 * @property Doctrine_Collection $Clasificacion
 * @property Doctrine_Collection $Entrenador
 * @property Doctrine_Collection $Jugador
 * @property Doctrine_Collection $Partido
 * @property Doctrine_Collection $Partido_3
 * 
 * @method integer             getIdequipo()      Returns the current record's "idequipo" value
 * @method integer             getNumjugadores()  Returns the current record's "numjugadores" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method integer             getIdclub()        Returns the current record's "idclub" value
 * @method string              getImagen()        Returns the current record's "imagen" value
 * @method Club                getClub()          Returns the current record's "Club" value
 * @method Doctrine_Collection getClasificacion() Returns the current record's "Clasificacion" collection
 * @method Doctrine_Collection getEntrenador()    Returns the current record's "Entrenador" collection
 * @method Doctrine_Collection getJugador()       Returns the current record's "Jugador" collection
 * @method Doctrine_Collection getPartido()       Returns the current record's "Partido" collection
 * @method Doctrine_Collection getPartido3()      Returns the current record's "Partido_3" collection
 * @method Equipo              setIdequipo()      Sets the current record's "idequipo" value
 * @method Equipo              setNumjugadores()  Sets the current record's "numjugadores" value
 * @method Equipo              setNombre()        Sets the current record's "nombre" value
 * @method Equipo              setIdclub()        Sets the current record's "idclub" value
 * @method Equipo              setImagen()        Sets the current record's "imagen" value
 * @method Equipo              setClub()          Sets the current record's "Club" value
 * @method Equipo              setClasificacion() Sets the current record's "Clasificacion" collection
 * @method Equipo              setEntrenador()    Sets the current record's "Entrenador" collection
 * @method Equipo              setJugador()       Sets the current record's "Jugador" collection
 * @method Equipo              setPartido()       Sets the current record's "Partido" collection
 * @method Equipo              setPartido3()      Sets the current record's "Partido_3" collection
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipo');
        $this->hasColumn('idequipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numjugadores', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('idclub', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('imagen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Club', array(
             'local' => 'idclub',
             'foreign' => 'idclub'));

        $this->hasMany('Clasificacion', array(
             'local' => 'idequipo',
             'foreign' => 'idequipo'));

        $this->hasMany('Entrenador', array(
             'local' => 'idequipo',
             'foreign' => 'idequipo'));

        $this->hasMany('Jugador', array(
             'local' => 'idequipo',
             'foreign' => 'idequipo'));

        $this->hasMany('Partido', array(
             'local' => 'idequipo',
             'foreign' => 'idequipolocal'));

        $this->hasMany('Partido as Partido_3', array(
             'local' => 'idequipo',
             'foreign' => 'idequipovisitante'));
    }
}