<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Goles', 'doctrine');

/**
 * BaseGoles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgoles
 * @property integer $idpartido
 * @property integer $idjugador
 * @property integer $minuto
 * @property Jugador $Jugador
 * @property Partido $Partido
 * 
 * @method integer getIdgoles()   Returns the current record's "idgoles" value
 * @method integer getIdpartido() Returns the current record's "idpartido" value
 * @method integer getIdjugador() Returns the current record's "idjugador" value
 * @method integer getMinuto()    Returns the current record's "minuto" value
 * @method Jugador getJugador()   Returns the current record's "Jugador" value
 * @method Partido getPartido()   Returns the current record's "Partido" value
 * @method Goles   setIdgoles()   Sets the current record's "idgoles" value
 * @method Goles   setIdpartido() Sets the current record's "idpartido" value
 * @method Goles   setIdjugador() Sets the current record's "idjugador" value
 * @method Goles   setMinuto()    Sets the current record's "minuto" value
 * @method Goles   setJugador()   Sets the current record's "Jugador" value
 * @method Goles   setPartido()   Sets the current record's "Partido" value
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('goles');
        $this->hasColumn('idgoles', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idpartido', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idjugador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('minuto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jugador', array(
             'local' => 'idjugador',
             'foreign' => 'idjugador'));

        $this->hasOne('Partido', array(
             'local' => 'idpartido',
             'foreign' => 'idpartido'));
    }
}