<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Entrenador', 'doctrine');

/**
 * BaseEntrenador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $identrenador
 * @property integer $idpersona
 * @property integer $idequipo
 * @property integer $activo
 * @property Equipo $Equipo
 * @property Persona $Persona
 * 
 * @method integer    getIdentrenador() Returns the current record's "identrenador" value
 * @method integer    getIdpersona()    Returns the current record's "idpersona" value
 * @method integer    getIdequipo()     Returns the current record's "idequipo" value
 * @method integer    getActivo()       Returns the current record's "activo" value
 * @method Equipo     getEquipo()       Returns the current record's "Equipo" value
 * @method Persona    getPersona()      Returns the current record's "Persona" value
 * @method Entrenador setIdentrenador() Sets the current record's "identrenador" value
 * @method Entrenador setIdpersona()    Sets the current record's "idpersona" value
 * @method Entrenador setIdequipo()     Sets the current record's "idequipo" value
 * @method Entrenador setActivo()       Sets the current record's "activo" value
 * @method Entrenador setEquipo()       Sets the current record's "Equipo" value
 * @method Entrenador setPersona()      Sets the current record's "Persona" value
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntrenador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entrenador');
        $this->hasColumn('identrenador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idpersona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idequipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Equipo', array(
             'local' => 'idequipo',
             'foreign' => 'idequipo'));

        $this->hasOne('Persona', array(
             'local' => 'idpersona',
             'foreign' => 'idpersona'));
    }
}