<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGuardUserProfile', 'doctrine');

/**
 * BaseSfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusuario
 * @property integer $user_id
 * @property string $foto
 * @property integer $idpersona
 * @property sfGuardUser $SfGuardUser
 * @property Persona $Persona
 * @property Doctrine_Collection $Comentario
 * @property Doctrine_Collection $Noticia
 * 
 * @method integer             getIdusuario()   Returns the current record's "idusuario" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getFoto()        Returns the current record's "foto" value
 * @method integer             getIdpersona()   Returns the current record's "idpersona" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "SfGuardUser" value
 * @method Persona             getPersona()     Returns the current record's "Persona" value
 * @method Doctrine_Collection getComentario()  Returns the current record's "Comentario" collection
 * @method Doctrine_Collection getNoticia()     Returns the current record's "Noticia" collection
 * @method SfGuardUserProfile  setIdusuario()   Sets the current record's "idusuario" value
 * @method SfGuardUserProfile  setUserId()      Sets the current record's "user_id" value
 * @method SfGuardUserProfile  setFoto()        Sets the current record's "foto" value
 * @method SfGuardUserProfile  setIdpersona()   Sets the current record's "idpersona" value
 * @method SfGuardUserProfile  setSfGuardUser() Sets the current record's "SfGuardUser" value
 * @method SfGuardUserProfile  setPersona()     Sets the current record's "Persona" value
 * @method SfGuardUserProfile  setComentario()  Sets the current record's "Comentario" collection
 * @method SfGuardUserProfile  setNoticia()     Sets the current record's "Noticia" collection
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('foto', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('idpersona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Persona', array(
             'local' => 'idpersona',
             'foreign' => 'idpersona'));

        $this->hasMany('Comentario', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario'));

        $this->hasMany('Noticia', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario'));
    }
}