sf_guard_user_profile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUserProfile
    module:               sf_guard_user_profile
    prefix_path:          /sf_guard_user_profile
    column:               idusuario
    with_wildcard_routes: true

jugador:
  class: sfDoctrineRouteCollection
  options:
    model:                jugador
    module:               jugador
    prefix_path:          /jugador
    column:               idjugador
    with_wildcard_routes: true

comentario:
  class: sfDoctrineRouteCollection
  options:
    model:                comentario
    module:               comentario
    prefix_path:          /comentario
    column:               idcomentario
    with_wildcard_routes: true

noticia:
  class: sfDoctrineRouteCollection
  options:
    model:                noticia
    module:               noticia
    prefix_path:          /noticia
    column:               idnoticia
    with_wildcard_routes: true

directivo:
  class: sfDoctrineRouteCollection
  options:
    model:                directivo
    module:               directivo
    prefix_path:          /directivo
    column:               iddirectivo
    with_wildcard_routes: true

club:
  class: sfDoctrineRouteCollection
  options:
    model:                club
    module:               club
    prefix_path:          /club
    column:               idclub
    with_wildcard_routes: true

persona:
  class: sfDoctrineRouteCollection
  options:
    model:                persona
    module:               persona
    prefix_path:          /persona
    column:               idpersona
    with_wildcard_routes: true

entrenador:
  class: sfDoctrineRouteCollection
  options:
    model:                entrenador
    module:               entrenador
    prefix_path:          /entrenador
    column:               identrenador
    with_wildcard_routes: true

partido:
  class: sfDoctrineRouteCollection
  options:
    model:                partido
    module:               partido
    prefix_path:          /partido
    column:               idpartido
    with_wildcard_routes: true

clasificacion:
  class: sfDoctrineRouteCollection
  options:
    model:                clasificacion
    module:               clasificacion
    prefix_path:          /clasificacion
    column:               idclasificacion
    with_wildcard_routes: true

equipo:
  class: sfDoctrineRouteCollection
  options:
    model:                equipo
    module:               equipo
    prefix_path:          /equipo
    column:               idequipo
    with_wildcard_routes: true

jornada:
  class: sfDoctrineRouteCollection
  options:
    model:                jornada
    module:               jornada
    prefix_path:          /jornada
    column:               idjornada
    with_wildcard_routes: true

categoria:
  class: sfDoctrineRouteCollection
  options:
    model:                categoria
    module:               categoria
    prefix_path:          /categoria
    column:               idcategoria
    with_wildcard_routes: true

temporada:
  class: sfDoctrineRouteCollection
  options:
    model:                temporada
    module:               temporada
    prefix_path:          /temporada
    column:               idtemporada
    with_wildcard_routes: true

  
sf_guard_signin:
  url:   /default_index
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /salida
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

  # You can find more information about this file on the symfony website:
  # http://www.symfony-project.org/reference/1_4/en/10-Routing

  # default rules
homepage:
  url:   /
  param: { module: default, action: index }

  # generic rules
  # please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
