<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/15 18:10:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => 'geloSUAREZ2006',
  'name' => 'doctrine',
)),);
