<?php

/**
 * Clasificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    proy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Clasificacion extends BaseClasificacion
{
	public function __toString() {
		return $this->getNombre();
	}
	
	public function getNombreEquipo()
	{
		return $this->getEquipo()->getNombre();
	}
	
	static public function actualizar_clasificacion($partido){
		$jornadaslocal = Doctrine_Query::create()
			->select('*')
			->from('Clasificacion c')
			->innerjoin('c.Jornada j')
			->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
			->andWhere('c.idEquipo = ?', $partido->getIdequipolocal())
			->orderBy('c.idclasificacion desc')
			->limit('1')
			->execute();
		
		$jornadasvisitante = Doctrine_Query::create()
			->select('*')
			->from('Clasificacion c')
			->innerjoin('c.Jornada j')
			->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
			->andWhere('c.idEquipo = ?', $partido->getIdequipovisitante())
			->orderBy('c.idclasificacion desc')
			->limit('1')
			->execute();
			
		$equipolocal = Doctrine::getTable('Equipo')->find($partido->getIdequipolocal());
		$equipovisitante = Doctrine::getTable('Equipo')->find($partido->getIdequipovisitante());
		$jornadaa = Doctrine::getTable('Jornada')->find($partido->getIdjornada());
		$categoriaa = Doctrine::getTable('Categoria')->find($partido->getCategoria()->getIdCategoria());
		
		if ($partido->getGoleslocal() > $partido->getGolesvisitante() )
		{
			// Gana el local
			if($jornadaa['numjornada'] != '1'){
				// Si hay jornadas previas
				foreach($jornadaslocal as $jornada){
					// Equipo local
					$nuevo_local = new Clasificacion();
					$nuevo_local['Equipo'] = $equipolocal;
					$nuevo_local['Jornada'] = $jornadaa;
					$nuevo_local['Categoria'] = $categoriaa;
					$nuevo_local['puntos'] = $jornada->getPuntos()+3;
					$nuevo_local['favor'] = $jornada->getFavor()+$partido->getGoleslocal();
					$nuevo_local['contra'] = $jornada->getContra()+$partido->getGolesvisitante();
					$nuevo_local['jugados'] = $jornada->getJugados()+1;
					$nuevo_local['ganados'] = $jornada->getGanados()+1;
					$nuevo_local['empatados'] = $jornada->getEmpatados();
					$nuevo_local['perdidos'] = $jornada->getPerdidos();
					$nuevo_local->save();
				}
				
				foreach($jornadasvisitante as $jornada){
					// Equipo visitante
					$nuevo_visitante = new Clasificacion();
					$nuevo_visitante['Equipo'] = $equipovisitante;
					$nuevo_visitante['Jornada'] = $jornadaa;
					$nuevo_visitante['Categoria'] = $categoriaa;
					$nuevo_visitante['puntos'] = $jornada->getPuntos();
					$nuevo_visitante['favor'] = $jornada->getFavor()+$partido->getGolesvisitante();
					$nuevo_visitante['contra'] = $jornada->getContra()+$partido->getGoleslocal();
					$nuevo_visitante['jugados'] = $jornada->getJugados()+1;
					$nuevo_visitante['ganados'] = $jornada->getGanados();
					$nuevo_visitante['empatados'] = $jornada->getEmpatados();
					$nuevo_visitante['perdidos'] = $jornada->getPerdidos()+1;
					$nuevo_visitante->save();
				}
			}
			else{
				// Si es la primera jornada
			
				// Equipo local
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 1)
				->set('c.empatados', 0)
				->set('c.perdidos', 0)
				->set('c.favor', $partido->getGoleslocal())
				->set('c.contra', $partido->getGolesvisitante())
				->set('c.puntos', 3)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipolocal())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();
			
				// Equipo visitante
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 0)
				->set('c.empatados', 0)
				->set('c.perdidos', 1)
				->set('c.favor', $partido->getGolesvisitante())
				->set('c.contra', $partido->getGoleslocal())
				->set('c.puntos', 0)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipovisitante())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();
			}
			
		} elseif ( $partido->getGoleslocal() < $partido->getGolesvisitante())
		{
			// Gana el visitante
			if($jornadaa['numjornada'] != '1'){
				// Si hay jornadas previas
				foreach($jornadaslocal as $jornada){
					// Equipo local
					$nuevo_local = new Clasificacion();
					$nuevo_local['Equipo'] = $equipolocal;
					$nuevo_local['Jornada'] = $jornadaa;
					$nuevo_local['Categoria'] = $categoriaa;
					$nuevo_local['puntos'] = $jornada->getPuntos();
					$nuevo_local['favor'] = $jornada->getFavor()+$partido->getGoleslocal();
					$nuevo_local['contra'] = $jornada->getContra()+$partido->getGolesvisitante();
					$nuevo_local['jugados'] = $jornada->getJugados()+1;
					$nuevo_local['ganados'] = $jornada->getGanados();
					$nuevo_local['empatados'] = $jornada->getEmpatados();
					$nuevo_local['perdidos'] = $jornada->getPerdidos()+1;
					$nuevo_local->save();
				}
			
				foreach($jornadasvisitante as $jornada){
					// Equipo visitante
					$nuevo_visitante = new Clasificacion();
					$nuevo_visitante['Equipo'] = $equipovisitante;
					$nuevo_visitante['Jornada'] = $jornadaa;
					$nuevo_visitante['Categoria'] = $categoriaa;
					$nuevo_visitante['puntos'] = $jornada->getPuntos()+3;
					$nuevo_visitante['favor'] = $jornada->getFavor()+$partido->getGolesvisitante();
					$nuevo_visitante['contra'] = $jornada->getContra()+$partido->getGoleslocal();
					$nuevo_visitante['jugados'] = $jornada->getJugados()+1;
					$nuevo_visitante['ganados'] = $jornada->getGanados()+1;
					$nuevo_visitante['empatados'] = $jornada->getEmpatados();
					$nuevo_visitante['perdidos'] = $jornada->getPerdidos();
					$nuevo_visitante->save();
				}
			}
			else{
				// Si es la primera jornada
			
				// Equipo local
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 0)
				->set('c.empatados', 0)
				->set('c.perdidos', 1)
				->set('c.favor', $partido->getGoleslocal())
				->set('c.contra', $partido->getGolesvisitante())
				->set('c.puntos', 0)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipolocal())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();
			
				// Equipo visitante
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 1)
				->set('c.empatados', 0)
				->set('c.perdidos', 0)
				->set('c.favor', $partido->getGolesvisitante())
				->set('c.contra', $partido->getGoleslocal())
				->set('c.puntos', 3)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipovisitante())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();

			}
		} else 
		{
			// Empate
			if($jornadaa['numjornada'] != '1'){
				// Si hay jornadas previas
				foreach($jornadaslocal as $jornada){
					// Equipo local
					$nuevo_local = new Clasificacion();
					$nuevo_local['Equipo'] = $equipolocal;
					$nuevo_local['Jornada'] = $jornadaa;
					$nuevo_local['Categoria'] = $categoriaa;
					$nuevo_local['puntos'] = $jornada->getPuntos()+1;
					$nuevo_local['favor'] = $jornada->getFavor()+$partido->getGoleslocal();
					$nuevo_local['contra'] = $jornada->getContra()+$partido->getGolesvisitante();
					$nuevo_local['jugados'] = $jornada->getJugados()+1;
					$nuevo_local['ganados'] = $jornada->getGanados();
					$nuevo_local['empatados'] = $jornada->getEmpatados()+1;
					$nuevo_local['perdidos'] = $jornada->getPerdidos();
					$nuevo_local->save();
				}
			
				foreach($jornadasvisitante as $jornada){	
					// Equipo visitante
					$nuevo_visitante = new Clasificacion();
					$nuevo_visitante['Equipo'] = $equipovisitante;
					$nuevo_visitante['Jornada'] = $jornadaa;
					$nuevo_visitante['Categoria'] = $categoriaa;
					$nuevo_visitante['puntos'] = $jornada->getPuntos()+1;
					$nuevo_visitante['favor'] = $jornada->getFavor()+$partido->getGolesvisitante();
					$nuevo_visitante['contra'] = $jornada->getContra()+$partido->getGoleslocal();
					$nuevo_visitante['jugados'] = $jornada->getJugados()+1;
					$nuevo_visitante['ganados'] = $jornada->getGanados();
					$nuevo_visitante['empatados'] = $jornada->getEmpatados()+1;
					$nuevo_visitante['perdidos'] = $jornada->getPerdidos();
					$nuevo_visitante->save();
				}
			}
			else{
				// Si es la primera jornada
			
				// Equipo local
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 0)
				->set('c.empatados', 1)
				->set('c.perdidos', 0)
				->set('c.favor', $partido->getGoleslocal())
				->set('c.contra', $partido->getGolesvisitante())
				->set('c.puntos', 1)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipolocal())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();
			
				// Equipo visitante
				$q = Doctrine_Query::create()
				->update('Clasificacion c')
				->set('c.jugados', 1)
				->set('c.ganados', 0)
				->set('c.empatados', 1)
				->set('c.perdidos', 0)
				->set('c.favor', $partido->getGolesvisitante())
				->set('c.contra', $partido->getGoleslocal())
				->set('c.puntos', 1)
				->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria())
				->andWhere('c.idEquipo = ?', $partido->getIdequipovisitante())
				->andWhere('c.idJornada = ?', $partido->getJornada()->getIdjornada())
				->execute();
				
			}
		}
	}
	
	static public function actualizar_posiciones_clasificacion($partido){
		$clasificacion = Doctrine_Query::create()
			->select('*')
			->from('Clasificacion c')
			->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria() )
			->andWhere('c.idJornada = ?', $partido->getIdjornada() )
			->orderBy('c.puntos desc, c.favor desc, c.contra asc')
			->execute();
			
			
		$i=0;
		foreach ($clasificacion as $value) {
			$i++;
			$q = Doctrine_Query::create()
			->update('Clasificacion c')
			->set('c.posicion', $i)
			->where('c.idCategoria = ?', $partido->getCategoria()->getIdCategoria() )
			->andWhere('c.idJornada = ?', $partido->getIdjornada() )
			->andWhere('c.idEquipo = ?', $value->getIdequipo() )
			->execute();
		}
	}
}
