<?php

/**
 * DirectivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Directivo');
    }
}