<?php

/**
 * EntrenadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntrenadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntrenadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entrenador');
    }
}