<?php

/**
 * GolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Goles');
    }
}