<?php

/**
 * TemporadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemporadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemporadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Temporada');
    }
}