<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/14 20:46:06
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'noticia/index',
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
));
