<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/15 17:40:45
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administrar',
  ),
);
