generator:
  class: sfDoctrineGenerator
  param:
    model_class:           club
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          club
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
           title: Listado de clubs
           display: [Nombre, Fundacion, Campo, Capacidad]
      filter:  ~
      form:    ~
      edit:
        title: Modificando el club "%%nombre%%"
      new:     ~
