all:
   javascripts: [-*,jquery-1.5.1.min.js, jquery.livequery.js, jquery-ui-1.8.11.custom.min.js, ajax.js, jquery.printElement.js, prueba_print.js]
   metas:
    title: Deportivo - Club Deportivo Vallobin