indexSuccess:
   javascripts: [-*, jquery-1.5.1.min.js, jquery.dataTables.js, configura_tabla_jugadores.js]
   stylesheets: [paginador_1.css, paginador_2.css]
   metas:
    title: Jugadores - Club Deportivo Vallobin
showSuccess:
   metas:
    title: Jugador - Club Deportivo Vallobin