generator:
  class: sfDoctrineGenerator
  param:
    model_class:           noticia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          noticia
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
           title: Listado de noticias   
           display: [idNoticia, =titulo, cuerpo]
           fields: 
              cuerpo: { params: size=10 }
      filter:  ~
      form:    ~
      edit:
        title: Modificando la noticia "%%titulo%%"
      new:     ~
