<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/14 20:32:46
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Deportivo - Club Deportivo Vallobin', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('coolblue.css', '', array ());
  $response->addStylesheet('enhancements.css', '', array ());
  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('screen.css', '', array ());
  $response->addStylesheet('jquery-ui-1.8.11.custom.css', '', array ());
  $response->addStylesheet('compara_equipos.css', '', array ());
  $response->addStylesheet('jquery.fancybox-1.3.1.css', '', array ());
  $response->addJavascript('jquery-1.5.1.min.js', '', array ());
  $response->addJavascript('jquery.livequery.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.11.custom.min.js', '', array ());
  $response->addJavascript('ajax.js', '', array ());
  $response->addJavascript('jquery.printElement.js', '', array ());
  $response->addJavascript('prueba_print.js', '', array ());


